server.port=9092
spring.datasource.url= jdbc:mysql://localhost:3306/coffeShop?createDatabaseIfNotExist=true
spring.datasource.username= root
spring.datasource.password=

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto= update

# App Properties
bezkoder.app.jwtCookieName= bezkoder-jwt
bezkoder.app.jwtRefreshCookieName= bezkoder-jwt-refresh
bezkoder.app.jwtSecret= ======================BezKoder=Spring===========================
#bezkoder.app.jwtExpirationMs= 86400000
#bezkoder.app.jwtRefreshExpirationMs= 86400000
file.upload-dir=C:/Users/Dell/Desktop/IIT cours 26/Cross_platform/Coffe-Shop/coffe-shop-expo/assets/images

## For test
bezkoder.app.jwtExpirationMs= 3600000
bezkoder.app.jwtRefreshExpirationMs= 604800000
